kind: pipeline
type: docker
name: code-analysis

steps:
- name: unit-test
  image: registry.home.iloahz.com/iloahz/nlib-ci:latest
  commands:
  - go test ./... -json > report.json
  - go test ./... -coverprofile coverage.out
  - mkdir tests
  - mv report.json tests/
  - mv coverage.out tests/
- name: sonarqube
  image: registry.home.iloahz.com/iloahz/nlib-ci:latest
  environment:
    SONAR_TOKEN:
      from_secret: sonar_token
  commands:
  - sonar-scanner -Dsonar.projectKey=nlib -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.home.iloahz.com -Dsonar.login=$SONAR_TOKEN

---
kind: pipeline
type: docker
name: publish-docker-registry

steps:
- name: publish-docker-registry  
  image: plugins/docker
  settings:
    repo: registry.home.iloahz.com/iloahz/nlib
    tags: latest

---
kind: pipeline
type: ssh
name: deploy

server:
  host: pku.home.iloahz.com
  user: iloahz
  password:
    from_secret: pku_password

steps:
- name: deploy
  commands:
  - cd /mnt/data/docker/nlib
  - docker-compose down
  - docker-compose pull
  - docker-compose up -d

depends_on:
- publish-docker-registry
