kind: pipeline
type: docker
name: unit-test

steps:
- name: unit-test
  image: golang
  commands:
  - go test ./...

---
kind: pipeline
type: docker
name: publish-docker-registry

steps:
- name: publish-docker-registry  
  image: plugins/docker
  settings:
    repo: registry.home.iloahz.com/iloahz/nlib
    tags: latest

---
kind: pipeline
type: ssh
name: deploy

server:
  host: pku.home.iloahz.com
  user: iloahz
  password:
    from_secret: pku_password

steps:
- name: deploy
  commands:
  - cd /mnt/data/docker/nlib
  - docker-compose down
  - docker-compose pull
  - docker-compose up -d

depends_on:
- publish-docker-registry
