log-level: debug
api:
  addr: 0.0.0.0
  port: 9502
builtin:
  echo:
    enabled: true
  kv:
    enabled: true
    mongo:
      uri:
      database: nlib
      collection: kv
  logs:
    enabled: true
    mongo:
      uri:
      database: nlib
      collection: logs
  files:
    enabled: false
    minio:
      endpoint:
      access-key:
      secret-key:
      use-ssl: true
      bucket: nlib
