log-level: debug
api:
  addr: 0.0.0.0
  port: 9502
builtin:
  mongo:
  webdav:
    endpoint:
    user:
    password:
  samba:
    endpoint:
    user:
    password:
    share:
    path:
  minio:
    endpoint:
    access-key:
    secret-key:
    use-ssl: true
    bucket: nlib